appName: StockViewer

database:
  driverClass: org.postgresql.Driver
  user: stockviewer
  password: 12345
  url: jdbc:postgresql://localhost:5432/stockdb

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

assets:
  overrides:
    /: public/

server:

  rootPath: '/api/*'
  type: simple
  applicationContextPath: /application
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  requestLog:
    appenders:
      - type: file
        currentLogFilename: var/log/stockviewer-requests.log
        archive: false
        timeZone: UTC
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: var/log/stockviewer.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: var/log/stockviewer-%d.log
      archivedFileCount: 5
      timeZone: UTC